# Generated by Django 5.2.17 on 2026-09-15 02:29

import bookings.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("requested_start_time", models.DateTimeField()),
                ("service_end_time", models.DateTimeField()),
                ("calendar_blocked_until", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("declined", "Declined"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                            ("payment_failed", "Payment failed"),
                            ("manually_approved", "Manually approved"),
                        ],
                        default="pending",
                        max_length=32,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[("online", "Online"), ("offline", "Offline")],
                        max_length=16,
                    ),
                ),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "deposit_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "amount_due_today",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("full_payment_required", models.BooleanField(default=False)),
                ("policy_acknowledged", models.BooleanField(default=False)),
                (
                    "stripe_setup_intent_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "stripe_payment_intent_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("proof_url", models.URLField(blank=True, default="")),
                ("proof_note", models.TextField(blank=True, default="")),
                ("decline_reason", models.TextField(blank=True, default="")),
                ("manual_override_note", models.TextField(blank=True, default="")),
                ("needs_resolution", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "manage_token",
                    models.CharField(
                        default=bookings.models.generate_manage_token,
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("reschedule_count", models.PositiveIntegerField(default=0)),
                (
                    "arrival_status",
                    models.CharField(
                        choices=[
                            ("none", "Not yet recorded"),
                            ("arrived", "Arrived"),
                            ("no_show", "No-show"),
                        ],
                        default="none",
                        max_length=16,
                    ),
                ),
                ("arrival_note", models.TextField(blank=True, default="")),
                ("archived", models.BooleanField(default=False)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to="clients.client",
                    ),
                ),
            ],
            options={
                "ordering": ["-requested_start_time"],
            },
        ),
        migrations.CreateModel(
            name="BookingItem",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name_snapshot", models.CharField(max_length=160)),
                ("price_snapshot", models.DecimalField(decimal_places=2, max_digits=8)),
                ("duration_snapshot", models.PositiveIntegerField()),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="bookings.booking",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="catalog.service",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(fields=["status"], name="bookings_bo_status_233e96_idx"),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["requested_start_time"], name="bookings_bo_request_0e842e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["manage_token"], name="bookings_bo_manage__b32f45_idx"
            ),
        ),
    ]
