# Generated by Django 5.2.17 on 2026-09-15 02:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=160)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=32)),
                ("strike_count", models.PositiveIntegerField(default=0)),
                ("reschedule_count_lifetime", models.PositiveIntegerField(default=0)),
                ("high_risk_flag", models.BooleanField(default=False)),
                ("high_risk_cleared_note", models.TextField(blank=True, default="")),
            ],
            options={
                "indexes": [
                    models.Index(fields=["email"], name="clients_cli_email_56b9fc_idx"),
                    models.Index(fields=["phone"], name="clients_cli_phone_164f4c_idx"),
                ],
            },
        ),
    ]
